/** Blog post slugs only — used by sitemap so we never import full POSTS (React content). */

export const BLOG_POST_SLUGS = [
  'arsenic-in-well-water-epa-limit-and-treatment',
  'best-countertop-water-filter',
  'best-ro-system-for-pfas-removal',
  'best-under-sink-water-filter',
  'best-water-filter-for-lead-removal',
  'best-water-filter-gaithersburg-md',
  'best-water-filter-pitcher-2025',
  'best-whole-house-water-filter',
  'boil-water-advisory-what-to-do-and-how-long',
  'bottled-water-vs-tap-water-cost-safety-and-pfas',
  'chloramine-vs-chlorine-in-tap-water',
  'chromium-6-in-drinking-water-should-you-worry',
  'disinfection-byproducts-tthm-haa5-explained',
  'fluoride-in-tap-water-safe-or-not',
  'hard-water-explained-scale-softeners-and-your-taps',
  'how-to-read-your-consumer-confidence-report',
  'how-to-test-your-tap-water-mail-in-labs-explained',
  'is-new-york-city-tap-water-safe-2026',
  'is-pfas-in-my-tap-water',
  'is-tap-water-safe-to-drink',
  'lead-in-tap-water-signs-and-symptoms',
  'microplastics-in-drinking-water-what-we-know',
  'moving-to-new-city-water-quality-check',
  'nitrate-in-well-water-infants-and-pregnancy',
  'pfas-in-new-york-city-water',
  'pfas-in-san-antonio-water',
  'private-well-water-testing-101',
  'radon-in-drinking-water',
  'refrigerator-water-filters-what-they-actually-remove',
  'reverse-osmosis-pros-and-cons',
  'san-antonio-water-quality',
  'tap-water-safety-during-pregnancy',
  'top-10-cities-hardest-tap-water',
  'top-10-most-pfas-contaminated-cities',
  'waterdrop-g3p600-vs-aquasana-smartflow',
  'waterdrop-k19s-vs-aquatru-classic',
  'what-does-epa-water-violation-mean',
  'what-is-ppm-ppb-ppt-water-quality',
  'what-water-filter-removes-pfas',
  'whole-house-water-filter-vs-under-sink-which-to-choose',
  'why-distilled-water-and-reverse-osmosis-are-best-for-high-purity',
  'why-does-tap-water-taste-bad',
] as const;

export const HIGH_PRIORITY_BLOG_SLUGS = new Set([
  'top-10-most-pfas-contaminated-cities',
  'san-antonio-water-quality',
  'pfas-in-san-antonio-water',
]);
