/** Editorial intros for high-traffic city water report pages */
export const PRIORITY_CITY_INTROS: Record<string, string> = {
  'san-antonio':
    "San Antonio draws its drinking water primarily from the Edwards Aquifer, one of the most productive artesian aquifers in the world — but that doesn't mean it arrives at your tap without a trace. The San Antonio Water System serves over 2 million people across the region, and like all large public water systems, it detects a range of contaminants during routine testing. Some are regulated and within legal limits; others exceed health guidelines set by independent scientists. The data below is pulled from 5 EPA databases so you can see exactly what's been found.",
  'new-york':
    'New York City\'s tap water has a reputation for quality — but EPA UCMR5 monitoring tells a more complicated story. PFOS was detected at 106 ppt in NYC\'s water system, more than 26 times the EPA\'s legal limit of 4 ppt. PFOA was found at 27.8 ppt (limit: 4 ppt) and PFHxS at 51.6 ppt (limit: 10 ppt). On top of that, buildings constructed before 1986 likely have lead service lines or lead solder inside — a problem the public water system can\'t fix from the plant. Here\'s what the full EPA dataset shows for New York City.',
  'los-angeles':
    "Los Angeles gets its water from three main sources — the Los Angeles Aqueduct, the State Water Project, and the Colorado River — and blends them depending on availability and season. That complexity means the contaminant profile can shift, and what's in your water depends partly on where in the city you live. LA has a well-documented history with water quality issues including chromium-6 and PFAS. The data below reflects what's been detected and reported across EPA databases.",
  houston:
    "Houston's water comes primarily from surface sources — the Trinity and San Jacinto rivers — which are more vulnerable to agricultural runoff, industrial discharge, and storm events than groundwater systems. The city's public water system serves one of the largest metro populations in the country, treating millions of gallons daily. Testing has detected a range of contaminants over the years, some regulated, some not. See the full picture below pulled from 5 EPA databases.",
  phoenix:
    "Phoenix relies heavily on the Colorado River, delivered via the Central Arizona Project canal — an open-air system that picks up agricultural runoff, sediment, and other contaminants along its 336-mile route before reaching treatment plants. The city also draws from Salt River Project reservoirs and local groundwater, creating a blended supply that varies by season. Phoenix water meets federal standards, but several contaminants are detected at levels that exceed independent health benchmarks. Here's what the data shows.",
  parkersburg:
    "Parkersburg, WV is the epicenter of America's PFAS crisis. For over 50 years, DuPont's Washington Works plant — located just outside the city — discharged PFOA directly into the Ohio River, contaminating the drinking water supply for tens of thousands of residents. The story inspired the film Dark Waters and resulted in the largest PFAS class-action settlement in US history. EPA UCMR5 monitoring shows PFOA at 179.5 ppt in Parkersburg's water — 45 times the EPA's legal limit of 4 ppt. HFPO-DA (a DuPont replacement chemical also known as GenX) was also detected at 8 ppt, above the 4 ppt EPA limit. Only reverse osmosis removes PFOA reliably at the tap.",
  'sugar-land':
    "Sugar Land, Texas shows the highest peak PFAS reading of any large Texas water system in EPA UCMR5 monitoring — 672 ppt of 6:2 FTS, a compound not yet covered by the EPA's six regulated PFAS limits. PFOA was also detected at 4.1 ppt, at the federal limit for that compound. The Brazos River corridor and Fort Bend County industrial legacy are the likely sources. Standard pitcher filters are not enough; NSF 58 reverse osmosis is what actually removes forever chemicals at the tap.",
  miami:
    "Miami-Dade Water and Sewer Authority serves nearly 3 million people from the Biscayne Aquifer — productive, but highly vulnerable to surface contamination. EPA monitoring found PFOS at 33 ppt (8× the legal limit) plus three other PFAS compounds above federal MCLs. Here's the full picture from EPA UCMR5 and SDWIS data for Miami-Dade.",
  fresno:
    "Fresno sits in California's San Joaquin Valley, where agricultural runoff and legacy pesticides have long complicated drinking water. EPA UCMR5 monitoring detected PFAS at 47 ppt in City of Fresno water, with PFOS, PFOA, and PFHxS above federal limits. The data below pulls from EPA databases so you can see what's been found and what filters actually work.",
  austin:
    "Austin's water comes from the Colorado River and the Highland Lakes — beautiful sources that still pick up PFAS and disinfection byproducts on the way to your tap. EPA UCMR5 data shows PFOS above the 4 ppt legal limit. Here's what Austin Water monitoring shows and what to do if you want PFAS removed at the faucet.",
  'fairfax-county':
    "Fairfax County is one of the largest suburban counties in the US, served by multiple public water systems drawing from the Potomac watershed. EPA UCMR5 monitoring in the county's service area shows PFAS at 21.9 ppt with PFOA and PFOS above federal MCLs. Use the data below to see detected compounds and filter options for Northern Virginia tap water.",
};
