/** Cities with strong Search Console impression volume — used for internal linking. */
export const SEARCH_DEMAND_CITIES = [
  {
    slug: 'gaithersburg',
    name: 'Gaithersburg',
    state: 'MD',
    href: '/water/gaithersburg',
    stat: 'WSSC Water · PFAS & testing context',
    queryHooks: ['Gaithersburg water quality', 'water testing Gaithersburg MD', 'WSSC tap water'],
  },
  {
    slug: 'san-antonio',
    name: 'San Antonio',
    state: 'TX',
    href: '/water/san-antonio',
    stat: '272 mg/L hardness · PFAS in UCMR5',
    queryHooks: ['San Antonio water quality', 'PFAS in San Antonio water', 'water contamination'],
  },
  {
    slug: 'raleigh',
    name: 'Raleigh',
    state: 'NC',
    href: '/water/raleigh',
    stat: 'GenX/PFAS zone · THM violations',
    queryHooks: ['Raleigh water quality', 'PFAS Raleigh NC', 'Wake County tap water'],
  },
  {
    slug: 'philadelphia',
    name: 'Philadelphia',
    state: 'PA',
    href: '/water/philadelphia',
    stat: 'Lead lines · Delaware River PFAS',
    queryHooks: ['Philadelphia water quality', 'Philly PFAS', 'Philadelphia lead pipes'],
  },
  {
    slug: 'san-diego',
    name: 'San Diego',
    state: 'CA',
    href: '/water/san-diego',
    stat: 'Imported water · PFAS & hardness',
    queryHooks: ['San Diego water quality', 'San Diego PFAS', 'San Diego hard water'],
  },
  {
    slug: 'baltimore',
    name: 'Baltimore',
    state: 'MD',
    href: '/water/baltimore',
    stat: 'Lead at tap · aging mains',
    queryHooks: ['Baltimore water quality', 'Baltimore lead water', 'city water testing Baltimore'],
  },
  {
    slug: 'fairfax-county',
    name: 'Fairfax County',
    state: 'VA',
    href: '/water/fairfax-county',
    stat: 'PFAS MCL flags · NoVA systems',
    queryHooks: ['Fairfax County water quality', 'Northern Virginia PFAS', 'Fairfax tap water'],
  },
  {
    slug: 'nashville',
    name: 'Nashville',
    state: 'TN',
    href: '/water/nashville',
    stat: 'Cumberland River · PFAS monitoring',
    queryHooks: ['Nashville water quality', 'Nashville tap water safe', 'Metro Nashville PFAS'],
  },
  {
    slug: 'chicago',
    name: 'Chicago',
    state: 'IL',
    href: '/water/chicago',
    stat: '400k+ lead lines · PFAS monitoring',
    queryHooks: ['Chicago tap water quality', 'Chicago lead pipes', 'Chicago water PFAS'],
  },
  {
    slug: 'houston',
    name: 'Houston',
    state: 'TX',
    href: '/water/houston',
    stat: '22.4 ppt PFAS · Ship Channel legacy',
    queryHooks: ['Houston tap water safe', 'Houston PFAS', 'Houston water quality 2026'],
  },
  {
    slug: 'phoenix',
    name: 'Phoenix',
    state: 'AZ',
    href: '/water/phoenix',
    stat: '7.4 ppt PFAS · very hard water',
    queryHooks: ['Phoenix tap water quality', 'Phoenix PFAS', 'Phoenix water hardness'],
  },
  {
    slug: 'new-york',
    name: 'New York City',
    state: 'NY',
    href: '/water/new-york',
    stat: 'PFOS 106 ppt · building lead risk',
    queryHooks: ['NYC tap water safe', 'NYC water PFAS', 'NYC lead pipes'],
  },
] as const;

export const SEARCH_DEMAND_EXTRA_LINKS = [
  { href: '/blog/best-water-filter-for-lead-removal', label: 'Best lead removal filters' },
  { href: '/blog/best-water-filter-hard-water', label: 'Hard water filter guide' },
  { href: '/worst-hardness', label: 'Hardest tap water rankings' },
  { href: '/water-hardness', label: 'Hardness by ZIP' },
  { href: '/worst-pfas-cities', label: 'PFAS MCL city list' },
  { href: '/rankings', label: 'State rankings table' },
] as const;
