/** Cities with strong Search Console impression volume — used for internal linking. */
export const SEARCH_DEMAND_CITIES = [
  {
    slug: 'gaithersburg',
    name: 'Gaithersburg',
    state: 'MD',
    href: '/water/gaithersburg',
    stat: 'WSSC Water · PFAS & testing context',
    queryHooks: ['Gaithersburg water quality', 'water testing Gaithersburg MD', 'WSSC tap water'],
  },
  {
    slug: 'san-antonio',
    name: 'San Antonio',
    state: 'TX',
    href: '/water/san-antonio',
    stat: '272 mg/L hardness · PFAS in UCMR5',
    queryHooks: ['San Antonio water quality', 'PFAS in San Antonio water', 'water contamination'],
  },
  {
    slug: 'chicago',
    name: 'Chicago',
    state: 'IL',
    href: '/water/chicago',
    stat: '400k+ lead lines · PFAS monitoring',
    queryHooks: ['Chicago tap water quality', 'Chicago lead pipes', 'Chicago water PFAS'],
  },
  {
    slug: 'houston',
    name: 'Houston',
    state: 'TX',
    href: '/water/houston',
    stat: '22.4 ppt PFAS · Ship Channel legacy',
    queryHooks: ['Houston tap water safe', 'Houston PFAS', 'Houston water quality 2026'],
  },
  {
    slug: 'phoenix',
    name: 'Phoenix',
    state: 'AZ',
    href: '/water/phoenix',
    stat: '7.4 ppt PFAS · very hard water',
    queryHooks: ['Phoenix tap water quality', 'Phoenix PFAS', 'Phoenix water hardness'],
  },
  {
    slug: 'new-york',
    name: 'New York City',
    state: 'NY',
    href: '/water/new-york',
    stat: 'PFOS 106 ppt · building lead risk',
    queryHooks: ['NYC tap water safe', 'NYC water PFAS', 'NYC lead pipes'],
  },
  {
    slug: 'miami',
    name: 'Miami',
    state: 'FL',
    href: '/water/miami',
    stat: 'PFOS 33 ppt · MDWASA UCMR5',
    queryHooks: ['Miami tap water quality', 'Miami PFAS', 'Miami-Dade water safe'],
  },
  {
    slug: 'sugar-land',
    name: 'Sugar Land',
    state: 'TX',
    href: '/water/sugar-land',
    stat: '672 ppt 6:2 FTS peak · PFOA at MCL',
    queryHooks: ['Sugar Land PFAS', 'Sugar Land water quality', '6:2 FTS Texas'],
  },
  {
    slug: 'dallas',
    name: 'Dallas',
    state: 'TX',
    href: '/water/dallas',
    stat: 'PFAS MCL violations · chloramine DBPs',
    queryHooks: ['Dallas tap water quality', 'Dallas PFAS', 'Dallas water safe'],
  },
  {
    slug: 'los-angeles',
    name: 'Los Angeles',
    state: 'CA',
    href: '/water/los-angeles',
    stat: 'Chromium-6 · 11.4 ppt PFAS',
    queryHooks: ['LA tap water quality', 'Los Angeles PFAS', 'LA water chromium-6'],
  },
] as const;

export const SEARCH_DEMAND_EXTRA_LINKS = [
  { href: '/worst-hardness', label: 'Hardest tap water rankings' },
  { href: '/water-hardness', label: 'Hardness by ZIP' },
  { href: '/worst-pfas-cities', label: 'PFAS MCL city list' },
  { href: '/rankings', label: 'State rankings table' },
] as const;
